### ISSUE TITLE
As an admin I want to create episodes so that I can share a podcast episode with the world

### ISSUE THREAD

**Issue by queso** [thespacedojo/microphone#1]

**Comment by queso** [comment]
Use ace editor? (check with @hellogerard on what package he uses for the blog) to handle the input.

We need:
- [x] Title
- [x] Text
- [x] File

**Comment by queso** [comment]
@cfly15 which s3 package did you say you used before?

**Comment by ryw** [comment]
Upload help — https://github.com/Lepozepo/S3/pull/6#issuecomment-34923281

Looks like we need to not use the S3 helper and instead call the method ourselves.
